spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/home/sprhegde/order-mgmt/config
          #search-locations: D:/OrderManagement/conf
          #search-locations: classpath:/shared
  profiles:
     active: native
  security:
    user:
      password: Shiva123   

server:
  port: 8888


