spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/home/sprhegde/order-mgmt/config
          #search-locations: C:/ORDER_MGMT_CONFIG_FILES/shared
          #search-locations: classpath:/shared
  profiles:
     active: native

server:
  port: 8888

security:
  user:
    password: Shiva123
