language: java
jdk: oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_eedcd202a36a_key -iv $encrypted_eedcd202a36a_iv -in test-f904dbc21a30.json.enc -out test-f904dbc21a30.json -d
- openssl aes-256-cbc -K $encrypted_957fbac0400e_key -iv $encrypted_957fbac0400e_iv -in sprhegde-d8b0d97ec19d.json.enc -out sprhegde-d8b0d97ec19d.json -d
- chmod +x mvnw
script:
- mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: releases
  api_key:
    secure: sh7oRlzgKaT7CevmNDz9/nqelUwUz+MYeafXltWd1r3PSP/7rryNoscjlWvbHy2sDYpCHR1+r8Sc9R1UNFOYmI8lvbrxVyWrZ3SLWE1E/Y1m/GEUO5rlz79dFTIl9TgVajGcU7SaG7ywYVQ3YBQfpmZS4hSWjiDPuSDOk/b7Vc/ZGha8X8yp4dhtqQRDKNwH1KhKaK3yxFbNSckbfZiOmr3vov5Shm16tQKHZKZH5f1Pqp9U0Kn05OaiFuNJidWBdOomqGEX97WSMc8uBAHSukSoLLz8Dhzn5s82MPMpJv4uCUNsu2T9YZlPxSc1K5vKAeU69AGDL4mScs5iyt3avTOgxSTpPucVdRpIhQa5l4eCV9Z87jh0ECD/7+8CWyRgoipRcrswXxfeNmzRHL6zhUW8Cihjs0EspYU7wd6nV2TJ0JwiYyixCp7fN3tBegFoGBYCR+LpCQby4krvP2Quczti6rF3MqprHAAXbMR+FC22u0jhlXrrz2Rh0ZSEi4WCri3cPIBVMo6+TnDn/dBkJXl3XywfKa5Cb/4oxS21toevJeoqjrFFGdLJm3rC5xMupuIyTjzxPwxfrISzVqlFtwJgLDnCbZc107bcEohI176kuuBHW2AKS+f6BUHL+NI+y8DsT46fwEUw2PT90/ZTR9VX+SR/jBSx0/JlDNOOTtc=
  file:
    - "/home/travis/.m2/repository/com/ordermgmt/config/1.0.0-SNAPSHOT/config-1.0.0-SNAPSHOT.jar"
    - "/home/travis/.m2/repository/com/ordermgmt/monitoring/0.0.1-SNAPSHOT/monitoring-0.0.1-SNAPSHOT.jar"
    - "/home/travis/.m2/repository/com/ordermgmt/registry/0.0.1-SNAPSHOT/registry-0.0.1-SNAPSHOT.jar"
    - "/home/travis/.m2/repository/com/ordermgmt/gateway/1.0-SNAPSHOT/gateway-1.0-SNAPSHOT.jar"
    - "/home/travis/.m2/repository/com/ordermgmt/auth-service/1.0-SNAPSHOT/auth-service-1.0-SNAPSHOT.jar"
    - "/home/travis/.m2/repository/com/ordermgmt/customer-service/1.0-SNAPSHOT/customer-service-1.0-SNAPSHOT.jar"
    - "/home/travis/.m2/repository/com/ordermgmt/notification-service/1.0.0-SNAPSHOT/notification-service-1.0.0-SNAPSHOT.jar"
    - "/home/travis/.m2/repository/com/ordermgmt/product-service/1.0-SNAPSHOT/product-service-1.0-SNAPSHOT.jar"
    
  on:
    repo: sprhegde/OrderMgmtRepo
    all_branches: true
    tags: true
sudo: required
dist: trusty
group: deprecated-2017Q4
services:
- docker
env:
  global:
  - secure: QnbzJkDlzmjR0Ea+ERJAj4G4WyyfRTQ8OM9URJ/xbdDI3rw7HwGYGiwINpYl1dCc0v+GEeRTsJu73bSNPYs2fV45Qa+BuUMwUKwQGnFIEEzjGez7YHeHL/FYT2dPI3EUHuc/40GSXXXW1YxGX/BvdKhVYQf9SlaXqSF4u6G0HLnqFrKMrwkqI6SnBrZTRXnqOUg+KXxNqseC7yjzi4LLUukLC66O8zvqVj/iz4jMdxJTGpSL5jSdDxypEdofYM5YYsaTza0pdluZVUEjIZQB+r6/qJI/yud9OvYoa6UylV5DOjtRpqf/7F+JapbKTQQEVvvIsSpHs4qfoTFpA1KjsGKKwKcCWiIsLr5kGdLb8H068nFPhYzKJ9c2QYu/I/Pt2fYyWrNSrjvb1hkj0Fbi1Q9VhtJUfeleoRagvMM7sWPG/fervlcynWcyc4XgG09uXLi0snJeP8lGCUO/yNQbM8yGENJ0tg3Gl4fD3IGJ/vsDt0tG6JMRMcWKIFdbvXseH4WodfjIy3jOryrgpJwYagIJspcx42z6PSx3cKgbYvgieJfQuhlQk8FhB3XphHaXJAH45Wh+bd2Rd5SPs8y9FMVQsVNyLY1ciB/PxMMgZZ9VAZfUSdQScNkZodegzFqokz0rq0lLO0hauy8U9MOQAUvCIUK1npVd/SETlDRYh44=
  - secure: JWFmn+SjILucEoyJ9+/xonNVcU4oxZdCppAOGmi1mmmQziQE8TW/5186dZURfeAU83aJN3dmzmvT7brH7ZcbkuJdxQwjQsAqt/ZTPImXxZKEqWTinDdL4VhXNOTpmqC02oOhu+bY+FsMzeGSQiIIws5yMYj0BA03tj8epNwgp6XnLG+7I5YHSqWUo5yJEO9ovDk3UpDwEVFsa0q8cKOaGvSxetYxTLQ0MDV2vaggDtTOiA8Vo0Oe8SM3kJ1eOQWUcB3LuSEyDaqaWCb4u6R9vXZImmFP8ikIm1+7VVaepXWlf9lPLLCZxZYEHV86mxHuZL2cjbObHjJ9KHJG1JDyuxc5EHBBt/WnW1LViahIXy5Aqrh0nDGSmmAUVVjhGIE7dKsSv5AkvZM1EcsFomq9EU6ZtyDB6/shV1onbijUIbfkyWplsQWNuIG0ifm9TJ2YIe6kzOikEswTC3W5AxfI5NDy1A5RhdM9SGoVpAcR/lFgjpki1fbF3h6ZFx9JM1oBjMxwbeM6sfXYWvsrVI85gsG0P8XnUetAZEfJQTV4ABXbXZvYd1dCRVPjUL32zAE9zmVNWGvG/oSUz9VAmd6QHUEZ/wzY/B+uCVxa+fi4XkCOwo9HbCUREaT8m0WpHUXMeaT+uc+cF9PWRYAZTS6AjPKuK0Xq5C2f8a2gfu/832s=
  - secure: Ir4CUbu6BPRYOtuRKhsQFJq4Bn10/rJVotaHycojZReEfPgpDQpAfU1pjRJla2Cly4Smi9pL2UGMAS1/3Ie0ra0I97be18DWmlaUl5Xepp455YhcKslhKU638a3nuQGasqngQ8q5oBzBsG7/eLUhRhoVQQ+NgN4by5YLRB4D9o239vJ5IWkfRElEavWqAYJrXbiq3MK7l+quCuMzJJNXw71sU4Eab/rHW9T7OLJfHMjdei13lbkR9iUki1AT7HkvPeEvhDIqfrFBXd1RsKcGfSJAqVkHLCtirCCuD1bAOvqH982CrnBTnGmOFjezJpd+EIRYEajtdr2wAwM/g8XqEblVdQRosorixputzvS+XzfeNOudwFBP/NkXXJ+RyBDnD8Nnblk4vyZN+Ivg+IktlWfezqS5mT4ABumwYLflA8LLtZQHwHdNqHU+YSYGW/0Mu5mXfQPnraaEYCQ7DZdp8S5pxNN9D8BQwMCuSeQDSjOy5n/a+JalmjdNyb6b/GYLqION0WZ+I829yD04tGVwS2rmoMJj24LIQBHKnvKJ/KYfU9F33PAR9fXZaRHCa1tuo65RiHxQKCPUvvrSwsYqDWmJm5C//HbYl12wkTnghfaMe9W5lHAOr7EV8JFqFq6mGLXwR4G+nyOpac56tmP+PFLR3b7+/yEaXWCrHFHz1YE=
  - COMMIT=${TRAVIS_COMMIT::8}
  
after_deploy:
- bash <(curl -s https://codecov.io/bash)
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components update
- gcloud --quiet components beta update
- gcloud --quiet components update kubectl
- gcloud --quiet config set project voltaic-azimuth-192414
- gcloud --quiet config set compute/zone us-central1-a
- docker login -u _json_key -p "$(cat test-f904dbc21a30.json)"  https://gcr.io
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`

# MONGODB
- export MONGO=gcr.io/voltaic-azimuth-192414/mongodb
- docker build -t $MONGO:$COMMIT ./mongodb
- docker tag $MONGO:$COMMIT $MONGO:$TAG
- docker push $MONGO 

# CONFIG
- export CONFIG=gcr.io/voltaic-azimuth-192414/config
- docker build -t $CONFIG:$COMMIT ./config
- docker tag $CONFIG:$COMMIT $CONFIG:$TAG
- docker push $CONFIG

# REGISTRY
- export REGISTRY=gcr.io/voltaic-azimuth-192414/registry
- docker build -t $REGISTRY:$COMMIT ./registry
- docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
- docker push $REGISTRY

  # GATEWAY
- export GATEWAY=gcr.io/voltaic-azimuth-192414/gateway
- docker build -t $GATEWAY:$COMMIT ./gateway
- docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
- docker push $GATEWAY

  # AUTH SERVICE
- export AUTH_SERVICE=gcr.io/voltaic-azimuth-192414/auth-service
- docker build -t $AUTH_SERVICE:$COMMIT ./auth-service
- docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
- docker push $AUTH_SERVICE

  # CUSTOMER SERVICE
- export CUSTOMER_SERVICE=gcr.io/voltaic-azimuth-192414/customer-service
- docker build -t $CUSTOMER_SERVICE:$COMMIT ./customer-service
- docker tag $CUSTOMER_SERVICE:$COMMIT $CUSTOMER_SERVICE:$TAG
- docker push $CUSTOMER_SERVICE

  # NOTIFICATION_SERVICE
- export NOTIFICATION_SERVICE=gcr.io/voltaic-azimuth-192414/notification-service
- docker build -t $NOTIFICATION_SERVICE:$COMMIT ./notification-service
- docker tag $NOTIFICATION_SERVICE:$COMMIT $NOTIFICATION_SERVICE:$TAG
- docker push $NOTIFICATION_SERVICE

  # MONITORING
- export MONITORING=gcr.io/voltaic-azimuth-192414/monitoring
- docker build -t $MONITORING:$COMMIT ./monitoring
- docker tag $MONITORING:$COMMIT $MONITORING:$TAG
- docker push $MONITORING

  # PRODUCT SERVICE
- export PRODUCT_SERVICE=gcr.io/voltaic-azimuth-192414/product-service
- docker build -t $PRODUCT_SERVICE:$COMMIT ./product-service
- docker tag $PRODUCT_SERVICE:$COMMIT $PRODUCT_SERVICE:$TAG
- docker push $PRODUCT_SERVICE

- gcloud config set project voltaic-azimuth-192414
- gcloud config set compute/zone us-central1-a
- gcloud auth activate-service-account --key-file sprhegde-d8b0d97ec19d.json
- gcloud compute scp /home/travis/build/sprhegde/OrderMgmtRepo/docker-compose.yml sprhegde@instance-1:~/order-mgmt/docker-compose_new.yml --zone us-central1-a
- gcloud compute ssh --zone us-central1-a sprhegde@instance-1 --command "cd order-mgmt
  docker login -u _json_key -p "$(cat test-f904dbc21a30.json)"  https://gcr.io
  source ~/.bashrc
  docker-compose down
  mv docker-compose.yml docker-compose_old.yml
  mv docker-compose_new.yml docker-compose.yml
  docker-compose up -d rabbitmq
  docker-compose up -d config
  docker-compose up -d registry
  docker-compose up -d"



