language: java
jdk: oraclejdk8

before_install:
- chmod +x mvnw

sudo: required
services:
- docker
env:
  global:
  - secure: QnbzJkDlzmjR0Ea+ERJAj4G4WyyfRTQ8OM9URJ/xbdDI3rw7HwGYGiwINpYl1dCc0v+GEeRTsJu73bSNPYs2fV45Qa+BuUMwUKwQGnFIEEzjGez7YHeHL/FYT2dPI3EUHuc/40GSXXXW1YxGX/BvdKhVYQf9SlaXqSF4u6G0HLnqFrKMrwkqI6SnBrZTRXnqOUg+KXxNqseC7yjzi4LLUukLC66O8zvqVj/iz4jMdxJTGpSL5jSdDxypEdofYM5YYsaTza0pdluZVUEjIZQB+r6/qJI/yud9OvYoa6UylV5DOjtRpqf/7F+JapbKTQQEVvvIsSpHs4qfoTFpA1KjsGKKwKcCWiIsLr5kGdLb8H068nFPhYzKJ9c2QYu/I/Pt2fYyWrNSrjvb1hkj0Fbi1Q9VhtJUfeleoRagvMM7sWPG/fervlcynWcyc4XgG09uXLi0snJeP8lGCUO/yNQbM8yGENJ0tg3Gl4fD3IGJ/vsDt0tG6JMRMcWKIFdbvXseH4WodfjIy3jOryrgpJwYagIJspcx42z6PSx3cKgbYvgieJfQuhlQk8FhB3XphHaXJAH45Wh+bd2Rd5SPs8y9FMVQsVNyLY1ciB/PxMMgZZ9VAZfUSdQScNkZodegzFqokz0rq0lLO0hauy8U9MOQAUvCIUK1npVd/SETlDRYh44=
  - secure: JWFmn+SjILucEoyJ9+/xonNVcU4oxZdCppAOGmi1mmmQziQE8TW/5186dZURfeAU83aJN3dmzmvT7brH7ZcbkuJdxQwjQsAqt/ZTPImXxZKEqWTinDdL4VhXNOTpmqC02oOhu+bY+FsMzeGSQiIIws5yMYj0BA03tj8epNwgp6XnLG+7I5YHSqWUo5yJEO9ovDk3UpDwEVFsa0q8cKOaGvSxetYxTLQ0MDV2vaggDtTOiA8Vo0Oe8SM3kJ1eOQWUcB3LuSEyDaqaWCb4u6R9vXZImmFP8ikIm1+7VVaepXWlf9lPLLCZxZYEHV86mxHuZL2cjbObHjJ9KHJG1JDyuxc5EHBBt/WnW1LViahIXy5Aqrh0nDGSmmAUVVjhGIE7dKsSv5AkvZM1EcsFomq9EU6ZtyDB6/shV1onbijUIbfkyWplsQWNuIG0ifm9TJ2YIe6kzOikEswTC3W5AxfI5NDy1A5RhdM9SGoVpAcR/lFgjpki1fbF3h6ZFx9JM1oBjMxwbeM6sfXYWvsrVI85gsG0P8XnUetAZEfJQTV4ABXbXZvYd1dCRVPjUL32zAE9zmVNWGvG/oSUz9VAmd6QHUEZ/wzY/B+uCVxa+fi4XkCOwo9HbCUREaT8m0WpHUXMeaT+uc+cF9PWRYAZTS6AjPKuK0Xq5C2f8a2gfu/832s=
  - secure: Ir4CUbu6BPRYOtuRKhsQFJq4Bn10/rJVotaHycojZReEfPgpDQpAfU1pjRJla2Cly4Smi9pL2UGMAS1/3Ie0ra0I97be18DWmlaUl5Xepp455YhcKslhKU638a3nuQGasqngQ8q5oBzBsG7/eLUhRhoVQQ+NgN4by5YLRB4D9o239vJ5IWkfRElEavWqAYJrXbiq3MK7l+quCuMzJJNXw71sU4Eab/rHW9T7OLJfHMjdei13lbkR9iUki1AT7HkvPeEvhDIqfrFBXd1RsKcGfSJAqVkHLCtirCCuD1bAOvqH982CrnBTnGmOFjezJpd+EIRYEajtdr2wAwM/g8XqEblVdQRosorixputzvS+XzfeNOudwFBP/NkXXJ+RyBDnD8Nnblk4vyZN+Ivg+IktlWfezqS5mT4ABumwYLflA8LLtZQHwHdNqHU+YSYGW/0Mu5mXfQPnraaEYCQ7DZdp8S5pxNN9D8BQwMCuSeQDSjOy5n/a+JalmjdNyb6b/GYLqION0WZ+I829yD04tGVwS2rmoMJj24LIQBHKnvKJ/KYfU9F33PAR9fXZaRHCa1tuo65RiHxQKCPUvvrSwsYqDWmJm5C//HbYl12wkTnghfaMe9W5lHAOr7EV8JFqFq6mGLXwR4G+nyOpac56tmP+PFLR3b7+/yEaXWCrHFHz1YE=
  - COMMIT=${TRAVIS_COMMIT::8}
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export SAMPLE=sprhegde/mongodb
  - docker build -t $SAMPLE:$COMMIT ./mongodb
  - docker tag $SAMPLE:$COMMIT $SAMPLE:$TAG
  - docker push $SAMPLE
