language: java
jdk: oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_eedcd202a36a_key -iv $encrypted_eedcd202a36a_iv -in sprhegde-d8b0d97ec19d.json.enc -out sprhegde-d8b0d97ec19d.json -d
- gcloud config set project voltaic-azimuth-192414
- gcloud config set compute/zone us-central1-a
- gcloud auth activate-service-account --key-file sprhegde-d8b0d97ec19d.json
- gcloud compute scp /home/travis/build/sprhegde/OrderMgmtRepo/docker-compose.yml sprhegde@instance-1:~/order-mgmt/docker-compose_new.yml --zone us-central1-a
- gcloud compute ssh --zone us-central1-a sprhegde@instance-1 --command "
  
  cd order-mgmt
  
  docker login -u _json_key -p '$(cat sprhegde-d8b0d97ec19d.json)'  https://gcr.io 
  
  

  docker run \
  
    -v /var/run/docker.sock:/var/run/docker.sock \
    
        -v '$PWD:/rootfs/$PWD' \
        
            -w='/rootfs/$PWD' \
            
                docker/compose:1.13.0 up
  
  "
  
  



