version: '2.1'
services:
  rabbitmq:
      image: rabbitmq:3-management
      restart: always
      ports:
        - 15672:15672

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: Shiva123
    image: gcr.io/voltaic-azimuth-192414/config:v2.4
    volumes:
      - /home/sprhegde/order-mgmt/config:/home/sprhegde/order-mgmt/config
    restart: always

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: Shiva123
    image: gcr.io/voltaic-azimuth-192414/registry:v2.4
    restart: always
    ports:
      - 8761:8761

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: Shiva123
    image: gcr.io/voltaic-azimuth-192414/gateway:v2.4
    restart: always
    ports:
      - 80:4000
      
  auth-service:    
    environment:
      CONFIG_SERVICE_PASSWORD: Shiva123
      NOTIFICATION_SERVICE_PASSWORD: Shiva123
      CUSTOMER_SERVICE_PASSWORD: Shiva123
      MONGODB_PASSWORD: Shiva123
    image: gcr.io/voltaic-azimuth-192414/auth-service:v2.4
    restart: always

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: Shiva123
    image: sprhegde/mongodb
    volumes:
      - /home/sprhegde/order-mgmt/auth-db:/data/db
    restart: always

  customer-service:
    environment:
      CONFIG_SERVICE_PASSWORD: Shiva123
      MONGODB_PASSWORD: Shiva123
      NOTIFICATION_SERVICE_PASSWORD: Shiva123
    image: gcr.io/voltaic-azimuth-192414/customer-service:v2.4
    restart: always

  customer-mongodb:
    environment:
      MONGODB_PASSWORD: Shiva123
    image: sprhegde/mongodb
    volumes:
      - /home/sprhegde/order-mgmt/customer-db:/data/db
    restart: always
    
  product-service:
    environment:
      CONFIG_SERVICE_PASSWORD: Shiva123
      MONGODB_PASSWORD: Shiva123
      NOTIFICATION_SERVICE_PASSWORD: Shiva123
    image: gcr.io/voltaic-azimuth-192414/product-service:v2.4
    restart: always

  product-mongodb:
    environment:
      MONGODB_PASSWORD: Shiva123
    image: sprhegde/mongodb
    volumes:
      - /home/sprhegde/order-mgmt/product-db:/data/db
    restart: always  

  notification-service:
    environment:
      CONFIG_SERVICE_PASSWORD: Shiva123
      MONGODB_PASSWORD: Shiva123
      NOTIFICATION_SERVICE_PASSWORD: Shiva123
    image: gcr.io/voltaic-azimuth-192414/notification-service:v2.4
    restart: always

  monitoring:
    environment:
      CONFIG_SERVICE_PASSWORD: Shiva123
    image: gcr.io/voltaic-azimuth-192414/monitoring:v2.4
    restart: always
    ports:
      - 9000:8080
