spring:
  data:
    mongodb:
      host: auth-mongodb
       #host: localhost
      username: user
      password: Shiva123
       #database: auth-db
      database: ordermgmtdb
      port: 27017

server:
  context-path: /uaa
  port: 5000
