hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
        path: /uaa/**
         #url: http://localhost:5000
        url: http://auth-service:5000
        stripPrefix: false
        sensitiveHeaders:
        
    customer-service:
        path: /customers/**
        serviceId: customer-service
        stripPrefix: false
        sensitiveHeaders:

    notification-service:
        path: /notifications/**
        serviceId: notification-service
        stripPrefix: false
        sensitiveHeaders:
        
    order-service:
        path: /orders/**
        serviceId: order-service
        stripPrefix: false
        sensitiveHeaders:
        
    product-service:
        path: /products/**
        serviceId: product-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000
