security:
  oauth2:
    client:
      clientId: customer-service
      clientSecret: Shiva123
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: Shiva123
      database: customer-db
      port: 27017

server:
  context-path: /customers
  port: 6000
