security:
  oauth2:
    client:
      clientId: product-service
      clientSecret: Mongo123
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: Mongo123
      database: product-db
      port: 27017

server:
  context-path: /products
  port: 7000
